### ISSUE TITLE
Screenmanager.push() isnt working

### ISSUE THREAD

**Issue by Amsanan** [crykn/libgdx-screenmanager#12]
[ScreenError.zip](https://github.com/crykn/libgdx-screenmanager/files/7773512/ScreenError.zip)
I've been testing the Screenmanager for some time and the transitioning from my Main Screen to another Screen and back isn't working, even though I added the super.show() method in both of them,
Could you help me to solve this?
Amsi

**Comment by crykn** [comment]
What you're doing in `MenueScreen` and `OptionScreen` looks correct. Are you overriding` render()` in your Game class (which has to extend `ManagedGame`) without calling `super.render()`?

**Comment by Amsanan** [comment]
I added super.render() to the Game class still no difference

**Comment by crykn** [comment]
Hm. Then I'd advise you to compare your code to the [example](https://github.com/crykn/libgdx-screenmanager/tree/master/example) in this repo and try to figure out where they differ.
