### ISSUE TITLE
BUG: Does not work on Android 

### ISSUE THREAD

**Issue by dkoding** [crykn/libgdx-screenmanager#15]
When compiling the shaders on Android (API level 29) I get this error:

    ERROR: 0:25: '=' : global variable initializers must be constant expressions
    ERROR: 0:26: '=' : global variable initializers must be constant expressions
 
That makes sense as there are constands defined outside the main() method.

Consider making the shaders compatible with 2.0 ES specification by moving constants into the main() method of the shader(s).

**Comment by crykn** [comment]
Which shader are you using? The library itself doesn't offer any and the `GLTransitionsShaderTransition` class doesn't add any constants to the shaders it is provided with: https://github.com/crykn/libgdx-screenmanager/blob/6572602a889155dfd21011254236c058efae5254/src/main/java/de/eskalon/commons/screen/transition/impl/GLTransitionsShaderTransition.java#L50-L91

**Comment by dkoding** [comment]
You are right. 

The problem was in the following shader:

```
  private String circleCropText =
            "uniform vec4 bgcolor; // = vec4(0.0, 0.0, 0.0, 1.0)\n" +
                    "\n" +
                    "vec2 ratio2 = vec2(1.0, 1.0 / ratio);\n" +
                    "float s = pow(2.0 * abs(progress - 0.5), 3.0);\n" +
                    "\n" +
                    "vec4 transition(vec2 p) {\n" +
                    "  float dist = length((vec2(p) - 0.5) * ratio2);\n" +
                    "  return mix(\n" +
                    "    progress < 0.5 ? getFromColor(p) : getToColor(p), bgcolor, step(s, dist)\n" +
                    "  );\n" +
                    "}\n";

```

I think I found it in one of your examples?

Changing it to this:

```
            "uniform vec4 bgcolor; // = vec4(0.0, 0.0, 0.0, 1.0)\n" +
                    "vec4 transition(vec2 p) {\n" +
                    "  vec2 ratio2 = vec2(1.0, 1.0 / ratio);\n" +
                    "  float s = pow(2.0 * abs(progress - 0.5), 3.0);\n" +
                    "  float dist = length((vec2(p) - 0.5) * ratio2);\n" +
                    "  return mix(\n" +
                    "    progress < 0.5 ? getFromColor(p) : getToColor(p), bgcolor, step(s, dist)\n" +
                    "  );\n" +
                    "}\n";

```

...fixed the problem.

The shader compiler is opinionated about constants. Variables defined outside the main method are considered constants I think... So in this case ratio2 and s would be constants in the first example.

**Comment by crykn** [comment]
I think `global variable initializers must be constant expressions` means that `ratio2` and `s` can't use uniforms and must be constant values instead. Anyways, I mentioned [on the wiki](https://github.com/crykn/libgdx-screenmanager/wiki/How-to-use-GL-Transitions#some-example-code) that there can be platform-specific limitations to compiling shaders.
