### ISSUE TITLE
GWT build issue

### ISSUE THREAD

**Issue by galloj** [crykn/libgdx-screenmanager#16]
I was getting following error when creating HTML build (library version 0.6.8):
```
> Task :html:compileGwt
Compiling module com.plebworks.snake.GdxDefinition
   Tracing compile failure path for type 'de.damios.guacamole.gdx.log.Logger'
      [ERROR] Errors in 'jar:file:/C:/Users/Jirka/.gradle/caches/modules-2/files-2.1/com.github.crykn.guacamole/gdx-gwt/0.3.2/63f54261a6c6dc4fb46bebe9b9916d9e80bb6b3d/gdx-gwt-0.3.2-sources.jar!/gwt/emu/de/damios/guacamole/gdx/log/Logger.java'
         [ERROR] Line 44: No source code is available for type text.formic.Stringf; did you forget to inherit a required module?
   [ERROR] Aborting compile due to errors in some input files
```

I was able to fix the problem by including following line into html dependencies of my project: `api 'com.github.tommyettinger:formic:0.1.4:sources'`

**Comment by crykn** [comment]
Hey, thanks for reporting this! libgdx-screenmanager-gwt is supposed to pull in that dependency on its own via [[1]](https://github.com/crykn/libgdx-screenmanager-gwt/blob/c8fa4fa0401189c87439c1e28b6e36b13cd53fdc/build.gradle#L37-L38) and [[2]](https://github.com/crykn/guacamole/blob/f41537aa428f00d6d924682128744357dbb81ef5/build.gradle#L87), but apparently transitive dependencies don't seem to work with the `:sources` qualifier... Ideally we'd be able to circumvent that, but I couldn't even find a description of this behaviour in the Gradle docs. For now, I'll just change the [wiki](https://github.com/crykn/libgdx-screenmanager/wiki/How-to-get-it-working-with-GWT) to reflect this.

**Comment by tommyettinger** [comment]
Hey, it's my formic library! I'll update the automatic dependency generation in gdx-liftoff to include formic for dependencies on libgdx-screenmanager-gwt 0.6.8 . It looks like I may instead need to update Guacamole to include it.
