### ISSUE TITLE
unable to get dependancies for 0.6.8 

### ISSUE THREAD

**Issue by KanedaFr** [crykn/libgdx-screenmanager#19]
With 0.6.8, on build, I got this error

```
:core-game:test: Could not resolve com.github.crykn.guacamole:gdx:0.3.2.
Required by:
    project :core-game > project :core > com.github.crykn:libgdx-screenmanager:0.6.8
```

No error if I use 0.6.7

I setup like expected
...
_maven { url 'https://jitpack.io' }_
...
on core:
        _api "com.github.crykn:libgdx-screenmanager:0.6.8"_
also tested with same error
        _implementation "com.github.crykn:libgdx-screenmanager:0.6.8"_

test with LibGDX 1.10.0 and 1.11.0, on Android Studio

**Comment by crykn** [comment]
Guacamole is distributed in the same way as libgdx-screenmanager itself, which is via Jitpack. [On their site](https://jitpack.io/#crykn/guacamole/0.3.2), version 0.3.2 seems to be uploaded and built properly, and on my end the dependency downloads without any problems. 

But I do seem to remember having trouble with broken artifacts in the past. You might be able to "fix" this by adding `compile "com.github.crykn.guacamole:gdx:v0.3.2"` (note the `v` before the version!) to your dependencies.

**Comment by therevills** [comment]
Just trying out Libgdx and I have the same issue with 0.6.8 and 0.6.9.

`project(":core") {
    apply plugin: "java-library"


    dependencies {

        api "com.badlogicgames.gdx:gdx:$gdxVersion"
        api "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
        implementation "com.github.crykn:libgdx-screenmanager:0.6.8"

    }
}
`

`:core:test: Could not resolve com.github.crykn.guacamole:gdx:0.3.2.
Required by:
    project :core > com.github.crykn:libgdx-screenmanager:0.6.8

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

`

If I change to 0.6.7, no errors :?

**Comment by crykn** [comment]
Have you tried the fix mentioned above?

**Comment by therevills** [comment]
![image](https://github.com/crykn/libgdx-screenmanager/assets/1094192/a3b6bc42-82e5-44b8-94ce-162e6775f1e9)
Yep :(

**Comment by crykn** [comment]
As suggested on Discord, removing `mavenLocal()` might fix it. Alternatively, you can also delete the `com/github/crykn` subfolder of `.m2/repository/` to trigger another download.
