### ISSUE TITLE
Adapter classes?

### ISSUE THREAD

**Issue by Frosty-J** [crykn/libgdx-screenmanager#20]
In libGDX, we have the likes of `public class InputAdapter implements InputProcessor`. Would something like this be sensible for libgdx-screenmanager? I've added the following (with more whitespace than seen here) to my own project, as I've never used `create()` (don't see much advantage to it over a constructor) or `dispose()` and rarely use `resize()`, and `hide()` normally only makes sense in conjunction with `show()`:

```java
public class ManagedScreenAdapter extends ManagedScreen {
  @Override protected void create() { }
  @Override public void hide() { }
  @Override public void render(float delta) { }
  @Override public void resize(int width, int height) { }
  @Override public void dispose() { }
}
```

I'm conscious that this takes us one step further away from `Screen`. Maybe there's a better way to spare the game code from empty methods - I haven't given it a great deal of thought.

**Comment by crykn** [comment]
Hey @Frosty-J!

> In libGDX, we have the likes of public class InputAdapter implements InputProcessor. Would something like this be sensible for libgdx-screenmanager?

The "idiomatic" approach in libgdx-screenmanager would be to define your own `Screen` class, i.e. `MyCoolGameBaseScreen`, which extends `ManagedScreen` and then use that in your `Game` class as follows: 

```java
public class MyCoolGame extends ManagedGame<MyCoolGameBaseScreen, ScreenTransition> {

   // ...

}
```

This has the advantage that one can add various other useful (game-specific) features to the base screen. But I can see that for most smaller games (and probably for jam games in particular) that is just more boilerplate code. Hence, I think adding a screen adapter makes sense and also aligns the library closer to the way libGDX itself is structured.

> as I've never used create() (don't see much advantage to it over a constructor)

The `create()` method has one main advantage: it allows you to defer initializing the screens. This can come in handy if you are using a loading screen to load your assets first (the loading screen can then call `ManagedScreen#initializeScreen()` which internally calls `create()`) or when you want to defer loading until the screen is first shown (by default `create()` is called after the screen is first pushed).
