### ISSUE TITLE
Help GLTransitionsShaderTransition

### ISSUE THREAD

**Issue by ninhle616** [crykn/libgdx-screenmanager#22]
I have read https://github.com/crykn/libgdx-screenmanager/wiki/How-to-use-GL-Transitions
But you can give me detail :
String circleCropText = "..."; // The code for the GL Transitions shader at hand
float ratio = ...; // = width / height
I do not fill :(. I am newest libgdx.

**Comment by crykn** [comment]
Hey @ninhle616!

`circleCropText` should be the code from [gl-transitions.com](https://gl-transitions.com/editor/CircleCrop).

`ratio` should be the width of your game divided by its height. To calculate that you can use `Gdx.graphics.getWidth()/Gdx.graphics.getHeight()`, but don't forget to update that when your game is resized.

**Comment by ninhle616** [comment]
@crykn 
I mean can you give details to get it running. Since I'm new, I don't know how to run
String circleCropText = "uniform vec4 bgcolor; // = vec4(0.0, 0.0, 0.0, 1.0)

vec2 ratio2 = vec2(1.0, 1.0 / ratio);
float s = pow(2.0 * abs(progress - 0.5), 3.0);" ?

**Comment by crykn** [comment]
You can use the shader transitions just like any other transitions in the library. So for example you can take the code example [here](https://github.com/crykn/libgdx-screenmanager/tree/ba21e369e3f48ac72142fd696ab633c0ae94da8d/example) and just change one of the transitions (for instance [this](https://github.com/crykn/libgdx-screenmanager/blob/ba21e369e3f48ac72142fd696ab633c0ae94da8d/example/MyGdxGame.java#L31-L32) one) to be a shader transition:

```java
String circleCropText = "..."; // The shader code from gl-transitons.com
float ratio = Gdx.graphics.getWidth() / Gdx.graphics.getHeight(); // don't forget to update the corresponding uniform when resizing the window

GLTransitionsShaderTransition circleCropTransition = new GLTransitionsShaderTransition(1F, Interpolation.smooth);
circleCropTransition.compileGLTransition("uniform float ratio;\n" + circleCropText);

circleCropTransition.getProgram().bind(); // you need to bind the ShaderProgram before uniforms can be set
circleCropTransition.getProgram().setUniformf("ratio", ratio);
circleCropTransition.getProgram().setUniformf("bgcolor", 0.0F, 0.0F, 0.0F, 1.0F);

screenManager.addScreenTransition("blending_transition", circleCropTransition); // either keep the name of the transition the same as in the example or change it and adapt MyGdxGame#L39 and GreenScreen#L30 accordingly
```
