### ISSUE TITLE
Can I add screen to screenmanager when it is required?

### ISSUE THREAD

**Issue by wangdong20** [crykn/libgdx-screenmanager#23]
Hi, I am glad I find this great screenmanager library in libgdx. I am wondering whether is possible to add screen to screenmanager when it is needed. In some cases, I have to initial new screen with parameter determined by user input. How can I make that rather than add screen before it is shown?

**Comment by crykn** [comment]
There are two ways you can go about this:

(1.) Just add the screen right before pushing it:
```java
game.getScreenManager().addScreen("blue_screen", new BlueScreen(myCoolData));
game.getScreenManager().pushScreen("blue_screen", "slicing_transition");
```

(2.) Alternatively, you can add the screen at the start and only later initialize it when it is pushed:
```java
game.getScreenManager().pushScreen("blue_screen", "slicing_transition", myCoolData);
```
In `BlueScreen`:
```java
public void show () {
    this.pushParams[0]... // this is 'myCoolData'
}
```

<br>

This whole thing with adding screens first, and then initializing stuff either in the constructor, `create()` or `show()` has created some confusion (see #20 for example). So, I'll have to think about simplifying that in a later version of libgdx-screenmanager.

**Comment by crykn** [comment]
Yes. If you use the same name, the old instance gets overridden.
