### ISSUE TITLE
resize() should be after show() in life cycle.

### ISSUE THREAD

**Issue by wangdong20** [crykn/libgdx-screenmanager#25]
After I implement the libgdx-screenmanager system, I just found the resize() called before show(), which make some variable not initialize at the correct time. I understand when switching screen, you may want to resize it first to draw it on the screen to make transition animation, but it make me confused if I am familiar with the original screen life cycle. Maybe you can disable the show() in ManagedScreen class. Another feature request, I would like sliding transition or push transition has bouncing effect, could you provide bouncing option for those already made transitions?

**Comment by crykn** [comment]
`resize()` being called before `show()` is based on `Game`'s behaviour. If you don't want that to happen, either don't call `super.show()` in your screen or move your initialisation code to `create()`.

> Another feature request, I would like sliding transition or push transition has bouncing effect, could you provide bouncing option for those already made transitions

This is already supported. Just provide the transition with an `Interpolation` instance that does that.
