### ISSUE TITLE
The currently bound framebuffer (0) doesn't match this one

### ISSUE THREAD

**Issue by yuriyfomin88** [crykn/libgdx-screenmanager#28]
Hello! First of all, I love the library!! Congratulations on the work!
I have a small problem when implementing it. If I don't use the transitions, everything works correctly. If I use the transition when loading the game, the transition works very well. However, the problem comes when I try to initialize the game screen, it breaks. I use an intermediate screen to load the assets and different resources.
Example:
Initialize the game: Works
@Override
public void create () {
super.create();

batch = new SpriteBatch();
assetLoader = AssetLoader.getInstance();
this.screenManager.setAutoDispose(true, true);
//setScreen(new MainMenuScreen(this));
this.screenManager.pushScreen(new MainMenuScreen(this), new HorizontalSlicingTransition(batch, 5, 1F));  
}

But when loading the game screen, it breaks and shows the following error:
It should be noted that I do not use any FrameBuffer.
Example: DONT WORK
 @Override
    public void render(float delta) {
        batch.begin();
        batch.draw(loadingTexture, Gdx.graphics.getWidth() / 2 - loadingTexture.getWidth() / 2, Gdx.graphics.getHeight() / 2 - loadingTexture.getHeight() / 2);
        batch.end();
        if(assetLoader.update()){
            game.getScreenManager().pushScreen(new ForestLevel(game, level, map), new HorizontalSlicingTransition(batch, 5, 1F)); //
            dispose();
        }
    }
Shows the following error:
_java.lang.IllegalStateException: The currently bound framebuffer (0) doesn't match this one. Make sure the nested framebuffers are closed in the same order they were opened in!
	at de.damios.guacamole.gdx.graphics.NestableFrameBuffer.end(NestableFrameBuffer.java:151)
	at de.damios.guacamole.gdx.graphics.NestableFrameBuffer.end(NestableFrameBuffer.java:126)
	at de.eskalon.commons.utils.ScreenFboUtils.screenToTexture(ScreenFboUtils.java:49)
	at de.eskalon.commons.screen.ScreenManager.render(ScreenManager.java:309)
	at de.eskalon.commons.screen.ScreenManager.render(ScreenManager.java:298)
	at de.eskalon.commons.core.ManagedGame.render(ManagedGame.java:75)
	at com.mygdx.la.ilustradora.LaIlustradora.render(LaIlustradora.java:44)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
	at com.mygdx.la.ilustradora.DesktopLauncher.main(DesktopLauncher.java:15)_

Thanks!!!

**Comment by crykn** [comment]
Hey @yuriyfomin88!

Since the transitions rely on framebuffers, you can't use a regular framebuffer in the `render()` method of your screens. You have to use a NestableFrameBuffer instead. More information on this can be found on the [wiki](https://github.com/crykn/libgdx-screenmanager/wiki/Custom-FrameBuffer-implementation) .

> It should be noted that I do not use any FrameBuffer.

Are you using any third-party libraries in your `ForestLevel`? Some of them, such as box2dlights for example, use framebuffers internally.

**Comment by yuriyfomin88** [comment]
Thank you for responding so quickly! Yes, I use both Box2D and LightBox2DLight. In fact, something strange happens. If I use the lights, I get the error I mentioned in the previous message.
_But if I don't use them (I deactivate them), I'm getting another type of error, related to Box2D:
> Task :desktop:DesktopLauncher.main()
Assertion failed: false, file /home/runner/work/libgdx/libgdx/extensions/gdx-box2d/gdx-box2d/jni/Box2D/Collision/Shapes/b2PolygonShape.cpp, line 158_

And the game screen tries to make the transition but it breaks.
![image](https://github.com/crykn/libgdx-screenmanager/assets/96110768/addf4e9a-2866-4479-97f5-e1600c04d966)

**Comment by crykn** [comment]
The lights bug can be fixed quite easily, check out [this page](https://github.com/crykn/libgdx-screenmanager/wiki/Custom-FrameBuffer-implementation#external-libraries). 

> But if I don't use them (I deactivate them), I'm getting another type of error, related to Box2D:
> > Task :desktop:DesktopLauncher.main()
> > Assertion failed: false, file /home/runner/work/libgdx/libgdx/extensions/gdx-box2d/gdx-box2d/jni/Box2D/Collision/Shapes/b2PolygonShape.cpp, line 158

This doesn't seem to be related to libgdx-screenmanager. The assertion fails if the [polygon is degenerate](https://github.com/libgdx/libgdx/blob/06562a4c3646cbc5ef6d1263f6182f017712b546/extensions/gdx-box2d/gdx-box2d/jni/Box2D/Collision/Shapes/b2PolygonShape.cpp#L158), which might be caused if your vertices are too close together. As stated in the [box2d docs](https://box2d.org/documentation/md__d_1__git_hub_box2d_docs__f_a_q.html), generally, your bodies should be somewhere between 0.1 and 10 in size, so scaling everything up might do the trick.

> And the game screen tries to make the transition but it breaks.

If I had to guess, you're not setting the viewport correctly. Check out the [docs](https://github.com/crykn/libgdx-screenmanager/wiki/Screen-Lifecycle) for the `ManagedScreen#render()` method (or the [examples](https://github.com/crykn/libgdx-screenmanager/tree/master/src/example)) and don't forget to update the viewport in your `resize()` method.

**Comment by yuriyfomin88** [comment]
Oh, thank you for this, I i will work on it!
"The lights bug can be fixed quite easily, check out [this page](https://github.com/crykn/libgdx-screenmanager/wiki/Custom-FrameBuffer-implementation#external-libraries)."

On the other hand, it's a bit strange because if I set the transitions to null, I'm not getting any error in Box2D. I'll have to investigate why this is happening! This is what worries me the most!!

And from what I see, the methods in render and size are also correct.
ForestLevel ->
@Override
    public void render(float dt) {
        gamePort.apply();
        if(!isPaused) {
            update(dt);
            game.batch.setProjectionMatrix(gamePort.getCamera().combined);

...
}
and
@Override
    public void resize(int width, int height) {
        gamePort.update(width, height);
        updateCameraPlayer(Gdx.graphics.getDeltaTime());
        stageConfiguraciones.getViewport().update(width, height, true);
        stageConfiguraciones.getViewport().apply(true);
    }
Thank you very much!

**Comment by yuriyfomin88** [comment]
I've solved it! It turns out I had poorly drawn polygons, and that's why the assertion was triggered. Once those polygons were corrected, everything is working properly! Now, I just need to implement the lights! Thank you so much!! And again, congratulations on the project! It's amazing!
