### ISSUE TITLE
Little ideas

### ISSUE THREAD

**Issue by pkruczynski** [crykn/libgdx-screenmanager#9]
**1.** It would be nice if de.eskalon.commons.screen.BlankScreen class would be a final Singleton, eg.: 

```
final class BlankScreen extends ManagedScreen {

	static
	private class SingletonHelper {
        	static
        	private final BlankScreen INSTANCE = new BlankScreen();
	}

	private BlankScreen() {}

	static
	public BlankScreen get() {
		return BlankScreen.SingletonHelper.INSTANCE;
	}

	@Override
	protected void create() {
		// do nothing
	}

	@Override
	public void render(float delta) {
		// do nothing
	}

	@Override
	public void hide() {
		// do nothing
	}

	@Override
	public void resize(int width, int height) {
		// do nothing
	}

	@Override
	public void dispose() {
		// do nothing
	}
}
```
Then from the de.eskalon.commons.screen.ScreenManager<S, T> class, it would be possible to get rid of the private field: BlankScreen blankScreen, and in the methods: initialize(), getLastScreen(), getCurrentScreen() refer directly to: ScreenBlank.get().

**2.** In the de.eskalon.commons.screen.transition.impl.HorizontalSlicingTransition class, I also noticed a problem with the divisibility of the viewport height in line 77. So I would quickly suggest changing it to:

`int sliceHeight = com.badlogic.gdx.math.MathUtils.ceil ((float) height / sliceCount); `

BTW, a great job. Thanks!

**Comment by crykn** [comment]
Hey @pkruczynski!

Regarding 1.: Thanks for the suggestion! I'm not really sure whether I like it better than the current implementation, but I understand where you're coming from and will think about it.

Regarding 2.: That is indeed a bug and will be fixed in the next release. If you want to use the fix right now, try version `dcbd15b90d`.
